<?php

use Drupal\Core\Cache\Cache;
use Drupal\node\Entity\Node;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function randstad_annual_node_presave(Node $node) {
  // Allows for clearing of blocks based on a node type.
  $tags = ['node_type:' . $node->getType()];
  Cache::invalidateTags($tags);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function randstad_annual_node_delete(Node $node) {
  // Allows for clearing of blocks based on a node type.
  $tags = ['node_type:' . $node->getType()];
  Cache::invalidateTags($tags);
}
